baseURL = 'http://erickmedeiros.com/'
languageCode = 'pt-br'
title = 'Erick Medeiros'
theme = 'ink-free'

paginate = 5

copyright = "© Copyright notice"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Software Developer"
	mode = "auto"
	wpm = 250
  favicon = "/favicon.png"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/erick-medeiros/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/erickmedeirosbr/"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://twitter.com/erickmedeirosbr/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 


search_bar = true
search_bar_placeholder = "Pesquisar meu site"


[services]
  [services.googleAnalytics]
    ID = 'G-CT7WGGWFED'