baseURL: "http://erickmedeiros.com/links"
languageCode: "pt-br"
title: "Erick Medeiros"
theme: "lynx"
publishDir: "public/links"

enableEmoji: true
disableKinds:
  - "taxonomy"
  - "term"

params:
  footer: disable
  author:
    name: "Erick Medeiros"
    headline: ""
    image: "author.jpeg"
    links:
      - linkedin: "https://www.linkedin.com/in/erickmedeirosbr"
      - github: "https://github.com/erick-medeiros"
      - link:
          href: https://erickmedeiros.com
          icon: link
          text: Site

markup:
  highlight:
    noClasses: false

  goldmark:
    renderer:
      unsafe: true
